# Generated by Django 3.0.5 on 2020-07-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contact_orders_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_prints',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sleeve',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(),
        ),
    ]
